### ISSUE TITLE
Disable 'Causal Effect Dependency' when activities are consecutive?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/activity-flow-editor#4]
@thomaspd 

In the Causal Relations Workbench, if a curator chooses 'Yes' for the consecutive activities, should we then disable the 'Causal Effect Dependency' options?

That would prevent a curator from choosing what I think is an incorrect sequence in the editor.

Thx.

**Comment by vanaukenk** [comment]
We need to update the activity flow editor as follows:

If the curator selects 'Yes' for the consecutive question, then the causal effect dependency option should be removed from available options.

If the curators selects 'No' for the consecutive question, then the causal effect dependency option should remain.

@tmushayahama - let me know if you want to go through the logic again and make sure that the resulting relations are correct.

Thx.

**Comment by tmushayahama** [comment]
@vanaukenk This is straightforward. thanks. Is it just the opposite of what it is doing now?

**Comment by vanaukenk** [comment]
Yes, it is the opposite.
I'll test that this change still produces all the desired relations before we put this into production.
Thanks.

**Comment by tmushayahama** [comment]
@vanaukenk @thomaspd what will be the behavior if both upstream and downstream are catalytic activities?
